version: '2.4'

services:
  healthy:
    image: busybox
    depends_on:
      database:
        condition: service_healthy

  database:
    image: mariadb:10.2
    ports:
      - 3306:3306
    volumes:
      - ./database/schema:/docker-entrypoint-initdb.d
    environment:
      MARIADB_ROOT_PASSWORD: secret
    healthcheck:
        test: mysqladmin ping --password=secret
        interval: 10s
        timeout: 5s
        retries: 5
