version: '3'

services:
  mysqld:
    image: mariadb:10.2
    ports:
      - 3306:3306
    volumes:
      - ./database/schema:/docker-entrypoint-initdb.d
    environment:
      MARIADB_ROOT_PASSWORD: secret
